config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts, controllers: { sessions: 'accounts/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top_pages#index"
  resources :test_search
  resources :law_firms, only: [:show, :index]
  resources :lawyer_profiles, only: :show
  resources :accounts, only: :show
  resources :request_law_firms, only: [:new, :create]
  resources :questions, only: [:show, :index]
  resources :clips, only: [:create, :destroy]
  resources :categories, only: [:index, :show]

  namespace :admin do
    root "home_page#index"
    resources :lawyer_profiles, only: [:index, :update, :show]
    resources :law_firms, only: [:index, :update]
    resources :accounts, only: [:index, :update]
    resources :articles, only: [:index, :destroy]
    resources :questions, only: [:index, :destroy]
    resources :answers, only: [:index, :destroy]
    namespace :approve do
      resources :lawyer_profiles, only: [:index, :update, :show]
    end
  end

  namespace :user do
    root "questions#index"
    resources :accounts, except: [:new, :create, :destroy]
    resources :questions
    resources :votes, except: [:show, :new, :edit]
    namespace :register_lawyer do
       resources :lawyer_profiles, only: [:new, :create, :update]
    end
    resources :clips, only: :index
    resources :notifies, only: :update
    resources :comments, only: [:update, :destroy]
    resources :reviews, except: [:index, :new, :edit]
  end

  resources :articles do
    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  end

  resources :answers do
    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  end

  namespace :lawyer do
    root "accounts#show"
    resources :lawyer_profiles, except: [:new, :create, :destroy]
    resources :accounts, except: [:new, :create, :destroy]
    resources :law_firms, except: [:show, :destroy]
    resources :request_law_firms, only: [:index, :destroy]
    resources :law_firm_members, only: [:index, :destroy]
    resources :add_law_firms, only: [:create, :index, :destroy]
    resources :out_law_firms, only: [:destroy]
    resources :articles
    resources :answers
    resources :questions, only: :index
    namespace :advertise do
      resources :history_advertises, only: [:new, :create]
    end
    namespace :draft do
      resources :articles, only: :index
    end
    resources :notifies, only: :index
    resources :clips, only: :index
  end

  namespace :search do
    root "top_pages#index"
    resources :top_pages, only: [:index]
  end

  namespace :follows do
    resources :follow_categories, only: [:index, :create, :destroy]
  end

  resources :tags, only: :show
end

app/views/layouts/shared/_account_buttons.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <span>
        <i class="fa fa-bell-o" aria-hidden="true" style="font-size:23px;color:white"></i>
        <i class="fa fa-asterisk <%= current_account.new_noti? ? '' : 'item-hide' %>"
          style="font-size:13px; color:red; position: absolute; top: 15px;" id="new_noti">
        </i>
      </span>
    </a>
    <ul class="dropdown-menu">
      <div class="notify_container">
        <div id="notifies">
          <% notifies = current_account.get_noti(5) %>
          <% if notifies.blank? %>
            <p id="notify">No notification</p>
          <% else %>
            <%= render partial: "shared/notifies/notify", collection: notifies, as: :notify %>
          <% end %>
        </div>
      </div>
    </ul>
  </li>

  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <span><%= image_tag current_account.account_avatar_url, size: "30x30", class: "no_margin" %></span>
      <span class="item"><%= current_account.name %></span>
      <span class="caret item"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= my_page_link current_account %>
      <li>
        <%= link_to t("sign_out"), destroy_account_session_path, method: :delete %>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/shared/_category_navigation.html.erb
<div class="grid no-margin" style="max-width: 1550px !important;">
  <div class="cate_navi">
    <ul class="nav sub_navi" role="navigation">
      <% Category.all.each do |category| %>
        <li class="nav__item"> <%= link_to category.name, category_path(category) %> </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/shared/_cover.html.erb
<div class="cover_image">
  <img src="https://dn07ar7mppjqz.cloudfront.net/uploads/image/picture/2641/eyecatch_00227_______________________________________.jpg" height="150px" class="image_cover">
</div>

app/views/layouts/shared/_flash.html.erb
<% Settings.flash.each do |key, value| %>
  <% unless flash[key].blank? %>
    <div class="alert <%= key[value] %>">
      <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
      <%= content_for?(:flash_errors) ? yield(:flash_errors) : flash[key] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/shared/_footer.html.erb
<div class="row">
  <div class="footer">
    <div class="col-md-4 col-md-offset-1">
      <div class="foot-intro">
        <p>© 2020 TOP LAWYER Co., Ltd. All Rights Reserved.</p>
      </div>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <div class="foot-intro">
        <p class="small_font">
          Mọi ý kiếm góp ý xin gửi về: TopLawyervn@gmail.com
        </p>
        <p class="small_font">
          To feedback, please email us: TopLawyervn@gmail.com
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_header.html.erb
<head>
  <title>TopLawyer</title>
  <data value="<%= current_account.nil? ? nil : current_account.id %>" id="current-account-id"></data>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application','data-turbolinks-track': 'reload', 'data-turbolinks-eval': 'false' %>
  <%= javascript_include_tag Ckeditor.cdn_url %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

app/views/layouts/shared/_login_buttons.html.erb
<ul class="nav navbar-nav navbar-right">
  <li>
    <%= link_to new_account_registration_path, {class: "item"} do %>
      <span class="glyphicon glyphicon-user"></span>
      <%= t ".sign_up" %>
    <% end %>
  </li>
  <li>
    <%= link_to new_account_session_path, {class: "item"} do %>
      <span class="glyphicon glyphicon-user"></span>
      <%= t ".sign_in" %>
    <% end %>
  </li>
</ul>

app/views/layouts/shared/_navigation_bar.html.erb
<div class="row">
  <div class="">
    <nav class="navbar navbar-inverse navbar-fixed-top" id="top-navi">
      <div class="col-md-10 col-md-offset-1">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand item" href="/"><%= t ".top_lawyer" %></a>
          </div>
          <ul class="nav navbar-nav">
            <li><%= link_to t(".articles"), root_path, class: "item" %></li>
            <li><%= link_to t(".questions"), questions_path, class: "item" %></li>
          </ul>

          <%= render "layouts/shared/top_search" %>

          <% if current_account.nil? %>
            <%= render "layouts/shared/login_buttons" %>
          <% else %>
            <%= render "layouts/shared/account_buttons" %>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/shared/_top_search.html.erb
<div class="">
  <form class="navbar-form navbar-left" action="<%= search_root_path %>">
    <div class="input-group" id="search_form" style="width: 250px;">
      <input type="text" class="form-control typeahead top_search_bar" placeholder=" <%= I18n.t "top_pages.search" %> " name="q" size="50">
    </div>
  </form>
</div>

app/views/layouts/shared/_top_search.js.erb
var substringMatcher = function(strs) {
  return function findMatches(q, cb) {
    var matches, substringRegex;

    // an array that will be populated with substring matches
    matches = [];

    // regex used to determine if a string contains the substring `q`
    substrRegex = new RegExp(q, 'i');

    // iterate through the pool of strings and for any string that
    // contains the substring `q`, add it to the `matches` array
    $.each(strs, function(i, str) {
      if (substrRegex.test(str)) {
        matches.push(str);
      }
    });

    cb(matches);
  };
};

var states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
  'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii',
  'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
  'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
  'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
  'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
  'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
  'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
  'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
];

$('#search_form .typeahead').typeahead({
  hint: true,
  highlight: true,
  minLength: 1
},
{
  name: 'states',
  source: substringMatcher(states)
});