config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts, controllers: { sessions: 'accounts/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top_pages#index"
  resources :test_search
  resources :law_firms, only: [:show, :index]
  resources :lawyer_profiles, only: :show
  resources :accounts, only: :show
  resources :request_law_firms, only: [:new, :create]
  resources :questions, only: [:show, :index]
  resources :clips, only: [:create, :destroy]
  resources :categories, only: [:index, :show]

  namespace :admin do
    root "home_page#index"
    resources :lawyer_profiles, only: [:index, :update, :show]
    resources :law_firms, only: [:index, :update]
    resources :accounts, only: [:index, :update]
    resources :articles, only: [:index, :destroy]
    resources :questions, only: [:index, :destroy]
    resources :answers, only: [:index, :destroy]
    namespace :approve do
      resources :lawyer_profiles, only: [:index, :update, :show]
    end
  end

  namespace :user do
    root "questions#index"
    resources :accounts, except: [:new, :create, :destroy]
    resources :questions
    resources :votes, except: [:show, :new, :edit]
    namespace :register_lawyer do
       resources :lawyer_profiles, only: [:new, :create, :update]
    end
    resources :clips, only: :index
    resources :notifies, only: :update
    resources :comments, only: [:update, :destroy]
    resources :reviews, except: [:index, :new, :edit]
  end

  resources :articles do
    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  end

  resources :answers do
    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  end

  namespace :lawyer do
    root "accounts#show"
    resources :lawyer_profiles, except: [:new, :create, :destroy]
    resources :accounts, except: [:new, :create, :destroy]
    resources :law_firms, except: [:show, :destroy]
    resources :request_law_firms, only: [:index, :destroy]
    resources :law_firm_members, only: [:index, :destroy]
    resources :add_law_firms, only: [:create, :index, :destroy]
    resources :out_law_firms, only: [:destroy]
    resources :articles
    resources :answers
    resources :questions, only: :index
    namespace :advertise do
      resources :history_advertises, only: [:new, :create]
    end
    namespace :draft do
      resources :articles, only: :index
    end
    resources :notifies, only: :index
    resources :clips, only: :index
  end

  namespace :search do
    root "top_pages#index"
    resources :top_pages, only: [:index]
  end

  namespace :follows do
    resources :follow_categories, only: [:index, :create, :destroy]
  end

  resources :tags, only: :show
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  def index
    search_content = params[:q]
    @articles = Article.search(title_or_content_cont: search_content).result(distinct: true)
      .page(params[:page]).per Settings.search.per_page.default
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:success] = t ".deleted"
      redirect_to admin_articles_path
    else
      flash[:error] = t ".delete_fail"
      redirect_to admin_articles_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

  def index
    redirect_to root_path
  end

  def show
    @article = Article.find(params[:id])
    @article = CreateToolTipService.new(@article, @article.all_tags).perform
    impressionist @article
    @author_articles = @article.account.articles.where.not(id: @article.id)
      .order(total_vote: :desc).limit(Settings.article.related)
    @related_articles = @article.related_articles
    @advertise_lawyers = Kaminari.paginate_array(Account.advertise_lawyer @article.category_id)
      .page(params[:page]).per Settings.advertise_number.category

    if current_account.present?
      @vote = @article.init_vote(current_account.id)
      @clip = @article.init_clip(current_account.id)
    end

    @commentable = @article
    @comments = @commentable.comments.hash_tree(limit_depth: 5)
    @comment = Comment.new
    if params[:parent_id] != nil
      @reply = @commentable.comments.new(parent_id: params[:parent_id])
    end
  end
end

app/controllers/lawyer/accounts_controller.rb
class Lawyer::AccountsController < Lawyer::BaseController
  def show
    @account = current_account
    @articles = current_account.articles.order(created_at: :desc).publish.page(params[:page])
      .per Settings.per_page.default
  end

  def edit
    @account = current_account
  end

  def update
    @account = current_account
    if current_account.update_attributes account_params
      flash[:success] = t ".updated"
      redirect_to lawyer_root_path
    else
      flash.now[:errors] = t ".update_fail"
      render :edit
    end
  end

  private
  def account_params
    params.require(:account).permit Account::ACCOUNT_ATTRIBUTES
  end
end

app/controllers/lawyer/add_law_firms_controller.rb
class Lawyer::AddLawFirmsController < Lawyer::BaseController
  def index
    @add_lfs = LawyerProfile.find_by(account_id: current_account).add_law_firms
  end
  def create
    add_lf = LawyerProfile.find_by(id: params[:add_id]).add_law_firms.new
    add_lf.law_firm_id = LawyerProfile.find_by(account_id: current_account).law_firm_id
    if add_lf.save
      redirect_to lawyer_law_firm_members_path(current_account)
      flash[:success] = t ".add_success"
    else
      flash.now[:alert] = t ".add_error"
    end
  end

  def destroy
    @add_lf = AddLawFirm.find(params[:id])
    if params[:approve] == "1"
      LawyerProfile.find_by(account_id: current_account).update_attributes(law_firm_id: @add_lf.law_firm_id)

      add_lfs = AddLawFirm.where(lawyer_profile_id: LawyerProfile.find_by(account_id: current_account).id)
      add_lfs.each do |alf|
        alf.destroy
      end
    end
    @add_lf.destroy
    redirect_to lawyer_add_law_firms_path
  end
end

app/controllers/lawyer/advertise/history_advertises_controller.rb
class Lawyer::Advertise::HistoryAdvertisesController < Lawyer::BaseController
  def new
    @history_advertise = current_account.history_advertises.build
    @categories = Category.all.pluck(:name, :id)
  end

  def create
    @categories = Category.all.pluck(:name, :id)
    @history_advertise = current_account.history_advertises.new history_advertise_params
    total_point = Point.advertise.first.point_per_time * @history_advertise.advertise_period
    if current_account.lawyer_profile.point >= total_point && update_infomation(@history_advertise.advertise_period)
      flash[:success] = t ".created"
      redirect_to lawyer_root_path
    else
      flash.now[:error] = t ".creat_fail"
      render :new
    end
  end

  private
  def history_advertise_params
    params.require(:history_advertise).permit HistoryAdvertise::HISTORY_ADVERTISE_ATTRIBUTES
  end

  def update_infomation point_amount
    history_point = ::CreateHistoryPointService.new(point: Point.advertise.first,
      account: current_account, amount: point_amount).perform
    ::UpdatePointLawyerService.new(current_account.lawyer_profile).perform
    @history_advertise.history_point_id = history_point.id
    @history_advertise.save
  end
end

app/controllers/lawyer/answers_controller.rb
class Lawyer::AnswersController < Lawyer::BaseController

  def new
    @answer = Question.find(params[:question_id]).answers.build
  end

  def create
    @answer = Answer.new lawyer_answer_params
    @answer.account_id = current_account.id
    if @answer.save
      flash[:success] = t ".created"
      ::Notifies::CreateNotificationService.new(current_account: current_account,
        target_account: @answer.question.account, model: @answer.question, action: :answer_question).perform
      redirect_to (params[:answer][:from_page].nil?) ? lawyer_questions_path : question_path(@answer.question)
    else
      flash.now[:error] = t ".create_fail"
      render :new
    end
    ::CreateHistoryPointService.new(point: Point.answer.first, account: @answer.account).perform
    ::UpdatePointLawyerService.new( @answer.account.lawyer_profile).perform
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update_attributes lawyer_answer_params
      flash[:success] = t ".updated"
      redirect_back(fallback_location: root_path)
    else
      flash[:errors] = t ".update_fail"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    if @answer.destroy
      flash[:success] = t ".deleted"
      redirect_back(fallback_location: root_path)
    else
      flash[:errors] = t ".delete_fail"
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def lawyer_answer_params
    params.require(:answer).permit Answer::ANSWER_ATTRIBUTES
  end

  def author_lawyer
    unless current_account.id == answer.account_id
      flash[:errors] = t ".access_denies"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/lawyer/articles_controller.rb
class Lawyer::ArticlesController < Lawyer::BaseController
  include Wicked::Wizard
  include SetupWizard

  before_action :article

  steps :new, :tag, :finish

  def index
    @articles = current_account.articles.publish.page(params[:page])
      .per Settings.per_page.default
  end

  def show
  end

  def new
    @article = Article.new
    @categories = Category.all
    @tags = Tag.all.where.not(name: @article.tags.pluck(:name))
    gon.tags = @article.tags.pluck(:name)
    render layout: "article"
  end

  def edit
    @article = Article.find(params[:id])
    @categories = Category.all
    @tags = Tag.all.where.not(name: @article.tags.pluck(:name))
    gon.tags = @article.tags.pluck(:name)
    render layout: "article"
  end

  def create
    params[:tag_list] = params[:tag_list].downcase! if params[:tag_list]
    @categories = Category.all
    case step
    when :new
      @article = Article.new
      render :new
    when :tag
      @article = current_account.articles.new(article_params)
      if @article.save
        if @article.publish?
          ::CreateHistoryPointService.new(point: Point.article.first, account: @article.account).perform
          ::UpdatePointLawyerService.new(@article.account.lawyer_profile).perform
        end
        render_wizard
        flash[:success] = t ".new"
      else
        puts @article.errors.full_messages
        flash.now[:alert] = t ".Please_correct_the_form"
        render :new
      end
    when :finish
      article = Article.find params[:article_id]
      article.tags.pluck(:id).each do |n|
        Tag.find(n).tag_descriptions.create account_id: current_account.id,
          content: params[:tags][n.to_s][:content]
      end
      # CreateToolTipService.new(article, article.all_tags).perform
      redirect_to article_path(article)
    end
  end

  def update
    params[:tag_list] = params[:tag_list].downcase! if params[:tag_list]
    @article = Article.find(params[:id])
    case step
    when :new
    when :tag
      from_draft = true if @article.draft?
      if @article.update_attributes article_params
        if from_draft
          ::CreateHistoryPointService.new(point: Point.article.first, account: @article.account).perform
          ::UpdatePointLawyerService.new(@article.account.lawyer_profile).perform
        end
        render_wizard
        flash[:success] = t ".updated"
      else
        puts @article.errors.full_messages
        flash.now[:error] = t ".fail"
        render :edit
      end
    when :finish
      article = Article.find params[:article_id]
      article.all_tags.each do |tag|
        create_or_update_tag_des tag, current_account.id, params
      end
      # CreateToolTipService.new(article, article.all_tags).perform
      redirect_to lawyer_articles_path
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def create_or_update_tag_des tag, account_id, params
    if td = tag.tag_descriptions.find_by(account_id: account_id)
      td.update_attributes content: params[:tags][n.to_s][:content]
    else
      tag.tag_descriptions.create account_id: current_account.id,
        content: params[:tags][n.to_s][:content]
    end
  end

  def article_params
    params.require(:article).permit Article::ARTICLE_ATTRIBUTES
  end

  def article
    return if params[:id].nil?
    article = Article.find params[:id]
    unless (current_account.Admin? || current_account == article.account)
      flash[:error] = t ".access_denies"
      redirect_to root_path
    end
  end
end

app/controllers/lawyer/base_controller.rb
class Lawyer::BaseController < ApplicationController
  layout "lawyer"
  helper LawyerHelper
  before_action :authenticate_account!, :authenticate_lawyer

  private
  def authenticate_lawyer
  	flash[:danger] = t ".access_denies"
    unless (current_account.Lawyer? || current_account.Admin?)
      redirect_to root_path
    end
  end
end

app/controllers/lawyer/clips_controller.rb
class Lawyer::ClipsController < Lawyer::BaseController
  def index
    ids = current_account.clips.pluck :article_id
    @articles = Article.where(id: ids.to_a).page(params[:pgae]).per Settings.paginate.default
  end
end

app/controllers/lawyer/draft/articles_controller.rb
class Lawyer::Draft::ArticlesController < Lawyer::BaseController
  def index
    @articles = current_account.articles.draft.page(params[:page])
      .per Settings.per_page.default
  end
end

app/controllers/lawyer/law_firm_members_controller.rb
class Lawyer::LawFirmMembersController < Lawyer::BaseController

  def index
    current_law_firm_id = LawyerProfile.find_by(account_id: current_account).law_firm_id
    current_law_firm = LawFirm.find(current_law_firm_id)
    if params[:q].present?
      @lawyer_profiles =LawyerProfile.no_law_firm.not_add_law_firm(current_law_firm.in_adding)
        .search(account_name_or_account_email_or_lawyer_id_or_address_or_phone_number_or_fax_number_or_introduction_cont: params[:q])
          .result(distinct: true).page(params[:page]).per Settings.search.per_page.default
    end
    @members = LawyerProfile.where(law_firm_id: current_law_firm_id, is_manager: 0)
      .page(params[:page]).per Settings.search.per_page.default
  end

  def show
  end

  def destroy
    if LawyerProfile.find(params[:id]).update_attributes(law_firm_id: nil)
      flash[:success] = t ".remove"
      redirect_to lawyer_law_firm_members_path(current_account)
    end
  end

end

app/controllers/lawyer/law_firms_controller.rb
class Lawyer::LawFirmsController < Lawyer::BaseController
  before_action :law_firm, only: [:edit, :update]

  def new
    @law_firm = current_account.law_firm || LawFirm.new
    @image = @law_firm.images.build
    @provinces = Province.all
  end

  def create
    @provinces = Province.all
    @law_firm = current_account.lawyer_profile.build_law_firm law_firm_params
    if @law_firm.save && update_lawyer
      flash[:success] = t ".created"
      redirect_to law_firm_path(@law_firm)
    else
      flash.now[:errors] = t ".create_fail"
      render :new
    end
  end

  def edit
    @law_firm = current_account.law_firm
    @provinces = Province.all
  end

  def update
    @provinces = Province.all
    if @law_firm.update_attributes(law_firm_params)
      flash[:success] = t ".updated"
      redirect_to law_firm_path(@law_firm)
    else
      flash.now[:errors] = t ".update_fail"
      render :edt
    end
  end

  private
  def law_firm_params
    params.require(:law_firm).permit LawFirm::LAWFIRM_ATTRIBUTES
  end

  def law_firm
    if current_account.manager_of params[:id]
      @law_firm = current_account.law_firm
    else
      flash[:errors] = t ".access_denies"
      redirect_to lawyer_root_path
    end
  end

  def update_lawyer
    current_account.lawyer_profile.update_attributes is_manager: true, law_firm_id: @law_firm.id
  end
end

app/controllers/lawyer/lawyer_profiles_controller.rb
class Lawyer::LawyerProfilesController < Lawyer::BaseController
  before_action :lawyer_profile, only: [:edit, :update]

  def edit
  end

  def update
    if @lawyer_profile.update_attributes lawyer_profile_params
      flash[:success] = t ".updated"
      redirect_to root_path
    else
      flash[:error] = t ".update_fail"
      render :edit
    end
  end

  private
  def lawyer_profile_params
    params.require(:lawyer_profile).permit LawyerProfile::LAWYER_PROFILE_ATTRIBUTES
  end

  def lawyer_profile
    @lawyer_profile = LawyerProfile.find params[:id]
    unless current_account.lawyer_profile == @lawyer_profile
      flash[:error] = t ".access_denies"
      redirect_to root_path 
    end
  end
end

app/controllers/lawyer/notifies_controller.rb
class Lawyer::NotifiesController < Lawyer::BaseController
  def index
    @notifies = current_account.notified
  end
end

app/controllers/lawyer/out_law_firms_controller.rb
class Lawyer::OutLawFirmsController < Lawyer::BaseController
  def destroy
    LawyerProfile.find_by(account_id: current_account).update_attributes(law_firm_id: nil)
    redirect_to law_firm_path(params[:id])
  end
end

app/helpers/lawyer_helper.rb
module LawyerHelper
  def law_firm_link lawyer_profile
    if lawyer_profile.law_firm.nil? || lawyer_profile.is_manager
      link_to t(".law_firm"), new_lawyer_law_firm_path
    else
      link_to t(".law_firm"), law_firm_path(lawyer_profile.law_firm)
    end
  end
end

app/views/lawyer/articles/_article.html.erb
<tr>
  <td><%= article.title %></td>
  <td><%= article.category_name %></td>
  <td><%= article.tag_list %></td>
  <td><%= article.status %></td>
  <td><%= article.total_vote %></td>
  <td>
    <%= link_to t(".show"), article_path(article) %>
    <% if article.account == current_account %>
      <%= link_to t(".edit"), edit_lawyer_article_path(article) %>
      <%= link_to t(".destroy"), lawyer_article_path(article) , method: :delete, data: { confirm: t(".confirm") } %>
    <% end %>
  </td>
</tr>

app/views/lawyer/articles/_form.html.erb
<div class="form-group">
  <%= f.label t(".title") %>
  <%= f.text_field :title, class: "form__input" %>
</div>

<div class="form-group">
  <%= f.label t(".status") %>
  <%= f.select :status, options_for_select([[t(".draft"), :draft], [t(".publish"), :publish]]), class: "form__input" %>
</div>

<div class="form-group">
  <%= f.label t(".categories") %>
  <%= f.select :category_id, options_for_select(categories.pluck(:name, :id)), class: "form_control" %>
</div>

<div class="form-group">
  <%= f.label t(".tag_list")%>
  <%= f.hidden_field :tag_list, class: "form__input", value: @article.tag_list.join(", "), readonly: true%>
  <ul id="show-tag-list" class="list-inline list_tag_show"></ul>
</div>

<div class="form-group">
  <input list="tag-data-list" id="input-tag" class="form__input" placeholder="input tags">
  <datalist id="tag-data-list">
    <% @tags.all.each do |tag| %>
      <option id="<%= tag.name %>" value="<%= tag.name %>"></option>
    <% end %>
  </datalist>
</div>

<div class="form-group" hidden>
  <%= f.label t(".total_vote") %>
  <%= f.number_field :total_vote, :value => 0, class: "form__input" %>
</div>

<div class="form-group">
  <%= f.label t(".content") %>
  <%= f.cktext_area :content, rows: 10, class: "form__input" %>
</div>
<script type="text/javascript">
  <%= render "shared/articles/tag_search.js"%>
</script>

app/views/lawyer/articles/_tag_search.js.erb
$(document).on('turbolinks:load', function(){
	$("#input-tag").change(function(){
	  var x = $("#input-tag").val();
	  var taglist = $("#article_tag_list").val();
	  $("#article_tag_list").val(taglist + "," + x);
	  document.getElementById("show-tag-list").innerHTML 
	  	+= '<li class="list-inline-item">' + x + '<i class="fa fa-close" id="tag-item" style="font-size:15px"></i></li>';
	  $("#input-tag").val("");
	});

	$(document).on("click", "#tag-item",function() {
		var delTag = ',' + $(this).parent().text();
		$(this).parent().remove();
		var tagList = $("#article_tag_list").val();
		tagList = tagList.replace(delTag, "");
		$("#article_tag_list").val(tagList);	
	});
});

app/views/lawyer/articles/edit.html.erb
<div class="col-md-12">
  <div class="section-title al-center mgt-90">
    <h4><%= t ".edit_article" %></h4>
  </div>

  <div class="section-body padding-arround pd-10">
    <%= form_for [:lawyer, @article], class: "article-form" do |f| %>
      <%= render "shared/errors_list", object: @article %>

      <%= render "form", f: f , categories: @categories%>
      <div class="form-group">
        <%= f.button t(".next"), type: :submit, name: :step, value: :tag,
          class: "form-control btn btn-primary" %>
        <!-- <%= f.submit t(".edit") , class: "form-control btn btn-primary" %> -->
      </div>
    <% end %>
  </div>
</div>

app/views/lawyer/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-9">
  <div class="section-title al-center">
    <h4><%= t ".article" %></h4>
  </div>
  <div class="section-body padding-arround">
    <%= render partial: "shared/articles/article", collection: @articles, as: :article,
      local: {current_account: current_account} %>
    <div class="row al-center"><%= paginate @articles %></div>
  </div>
</div>
<div class="col-md-3">
  <div class="section-body padding-arround al-center">
    <p><%= t ".create_new_article" %></p>
    <%= link_to t(".new_article"), new_lawyer_article_path, class: "btn--warning" %>
  </div>
</div>
<div class="col-md-3">
  <%= render "shared/lawyer_profiles/lawyer_statistis", account: current_account %>
</div>

app/views/lawyer/articles/new.html.erb
<div class="col-md-12">
  <div class="section-title al-center mgt-90">
    <h4><%= t ".create_article" %></h4>
  </div>

  <div class="section-body padding-arround pd-10">
    <%= form_for [:lawyer, @article], class: "article-form" do |f| %>
      <%= render "shared/errors_list", object: @article %>
      <%= render "form", f: f , categories: @categories%>
      <div class="form-group">
        <%= f.button t(".next"), type: :submit, name: :step, value: :tag,
          class: "form-control btn btn-primary" %>
        <!-- <%= f.submit "Create" , class: "form-control btn btn-primary" %> -->
      </div>
    <% end %>
  </div>
</div>

app/views/lawyer/articles/tag.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="section-title al-center">
    <h4><%= t ".add_tag_description" %></h4>
  </div>

  <div class="section-body padding-arround pd-10">
    <% tags = @article.all_tags %>
    <%= form_tag lawyer_articles_path, :html => { :method => :put } do %>
      <%= hidden_field_tag :article_id, @article.id %>
      <% for tag in tags %>
        <% td = tag.tag_descriptions.find_by(account_id: current_account.id) %>
        <% description = td.nil? ? "" : td.content %>
        <%= fields_for "tags[#{tag.id}]" do |f| %>
          <p>
            <span><%= tag.name %></span>
            <%= f.text_area :content, value: description, class: "form__input" %>
            <%= f.hidden_field :account_id, value: current_account.id %>
          </p>
        <% end %>
      <% end %>

      <%= submit_tag t(".finish"), name: :step, value: :finish, class: "form-control btn btn-primary" %>
    <% end %>
  </div>
</div>