config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts, controllers: { sessions: 'accounts/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top_pages#index"
  resources :test_search
  resources :law_firms, only: [:show, :index]
  resources :lawyer_profiles, only: :show
  resources :accounts, only: :show
  resources :request_law_firms, only: [:new, :create]
  resources :questions, only: [:show, :index]
  resources :clips, only: [:create, :destroy]
  resources :categories, only: [:index, :show]

  namespace :admin do
    root "home_page#index"
    resources :lawyer_profiles, only: [:index, :update, :show]
    resources :law_firms, only: [:index, :update]
    resources :accounts, only: [:index, :update]
    resources :articles, only: [:index, :destroy]
    resources :questions, only: [:index, :destroy]
    resources :answers, only: [:index, :destroy]
    namespace :approve do
      resources :lawyer_profiles, only: [:index, :update, :show]
    end
  end

  namespace :user do
    root "questions#index"
    resources :accounts, except: [:new, :create, :destroy]
    resources :questions
    resources :votes, except: [:show, :new, :edit]
    namespace :register_lawyer do
       resources :lawyer_profiles, only: [:new, :create, :update]
    end
    resources :clips, only: :index
    resources :notifies, only: :update
    resources :comments, only: [:update, :destroy]
    resources :reviews, except: [:index, :new, :edit]
  end

  resources :articles do
    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  end

  resources :answers do
    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  end

  namespace :lawyer do
    root "accounts#show"
    resources :lawyer_profiles, except: [:new, :create, :destroy]
    resources :accounts, except: [:new, :create, :destroy]
    resources :law_firms, except: [:show, :destroy]
    resources :request_law_firms, only: [:index, :destroy]
    resources :law_firm_members, only: [:index, :destroy]
    resources :add_law_firms, only: [:create, :index, :destroy]
    resources :out_law_firms, only: [:destroy]
    resources :articles
    resources :answers
    resources :questions, only: :index
    namespace :advertise do
      resources :history_advertises, only: [:new, :create]
    end
    namespace :draft do
      resources :articles, only: :index
    end
    resources :notifies, only: :index
    resources :clips, only: :index
  end

  namespace :search do
    root "top_pages#index"
    resources :top_pages, only: [:index]
  end

  namespace :follows do
    resources :follow_categories, only: [:index, :create, :destroy]
  end

  resources :tags, only: :show
end

app/models/law_firm.rb
class LawFirm < ApplicationRecord
  mount_uploader :avatar, ImageUploader

  has_many :lawyer_profiles
  has_many :images, as: :imageable
  belongs_to :province
  has_many :request_law_firms
  has_many :add_law_firms
  has_many :reviews, as: :reviewable
  has_many :accounts, through: :lawyer_profiles

  validates :name, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :address, presence: true

  accepts_nested_attributes_for :images, :reject_if => lambda { |a| a[:picture].blank? }, allow_destroy: true

  LAWFIRM_ATTRIBUTES = [:name, :mail, :address, :province_id, :phone_number, :fax, :working_start_time,
    :working_end_time, :introduction, images_attributes: [:picture]]

  def in_adding
    add_law_firms.pluck(:lawyer_profile_id)
  end

  def lf_avatar_url
    avatar_url(:avatar) || Settings.images.default_avatar
  end
end

app/controllers/admin/law_firms_controller.rb
class Admin::LawFirmsController < Admin::BaseController
  before_action :law_firm, only: :update

  def index
    search_content = params[:q]
    @law_firms = LawFirm.search(name_or_phone_number_or_fax_or_email_or_address_or_introduction_cont: search_content)
      .result(distinct: true).page(params[:page]).per Settings.search.per_page.default
  end

  def update
    if @law_firm.update_attributes is_active: params[:law_firm][:is_active]
      redirect_to admin_law_firms_path
      flash[:success] = t ".updated"
    else
      redirect_to admin_law_firms_path
      flash[:error] = t ".fail"
    end
  end

  private
  def law_firm
    @law_firm = LawFirm.find params[:id]
  end
end

app/controllers/law_firms_controller.rb
class LawFirmsController < ApplicationController
  def show
    @law_firm = LawFirm.find params[:id]
    @lawyer_profiles = @law_firm.lawyer_profiles
    @reviews = @law_firm.reviews
    if current_account.present?
      @request_lf = @law_firm.request_law_firms.find_by(account_id: current_account.id) || current_account.request_law_firms.new
      @law_profile = LawyerProfile.find_by(account_id: current_account)
    end
  end
end

app/controllers/lawyer/law_firms_controller.rb
class Lawyer::LawFirmsController < Lawyer::BaseController
  before_action :law_firm, only: [:edit, :update]

  def new
    @law_firm = current_account.law_firm || LawFirm.new
    @image = @law_firm.images.build
    @provinces = Province.all
  end

  def create
    @provinces = Province.all
    @law_firm = current_account.lawyer_profile.build_law_firm law_firm_params
    if @law_firm.save && update_lawyer
      flash[:success] = t ".created"
      redirect_to law_firm_path(@law_firm)
    else
      flash.now[:errors] = t ".create_fail"
      render :new
    end
  end

  def edit
    @law_firm = current_account.law_firm
    @provinces = Province.all
  end

  def update
    @provinces = Province.all
    if @law_firm.update_attributes(law_firm_params)
      flash[:success] = t ".updated"
      redirect_to law_firm_path(@law_firm)
    else
      flash.now[:errors] = t ".update_fail"
      render :edt
    end
  end

  private
  def law_firm_params
    params.require(:law_firm).permit LawFirm::LAWFIRM_ATTRIBUTES
  end

  def law_firm
    if current_account.manager_of params[:id]
      @law_firm = current_account.law_firm
    else
      flash[:errors] = t ".access_denies"
      redirect_to lawyer_root_path
    end
  end

  def update_lawyer
    current_account.lawyer_profile.update_attributes is_manager: true, law_firm_id: @law_firm.id
  end
end

app/views/law_firms/_law_firm_info.html.erb
<div id="home" class="tab-pane fade in active">
  <div class="content-trouble clearfix">
    <div class="row">
      <div class="col-md-12 mb-pd0">
        <div class="title-content">
          <h3>
            <font style="vertical-align: inherit;"><%= t ".word_law_firm"%></font>
          </h3>
        </div>
      </div>
    </div>
    <div class="description">
      <font style="vertical-align: inherit;">
        <%= law_firm.introduction %>
      </font>
    </div>
    <div class="row">
      <div class="col-md-12 mb-pd0">
        <div class="title-content">
          <h3>
            <font style="vertical-align: inherit;"><%= t ".profile"%></font>
          </h3>
        </div>
      </div>
    </div>

    <font style="vertical-align: inherit;">
      <table class="table">
        <tbody>
          <tr>
            <td><%= t ".name" %></td>
            <td><%= law_firm.name %></td>
          </tr>
          <tr>
            <td><%= t ".email" %></td>
            <td><%= law_firm.email %></td>
          </tr>
          <tr>
            <td><%= t ".address" %></td>
            <td><%= law_firm.address %></td>
          </tr>
          <tr>
            <td><%= t ".phone_number" %></td>
            <td><%= law_firm.phone_number %></td>
          </tr>
          <tr>
            <td><%= t ".fax_number" %></td>
            <td><%= law_firm.fax %></td>
          </tr>
          <tr>
            <td><%= t ".working_start_time" %></td>
            <td><%= law_firm.working_start_time.strftime("%I:%M") if law_firm.working_start_time.present? %></td>
          </tr>
          <tr>
            <td><%= t ".working_end_time" %></td>
            <td><%= law_firm.working_end_time.strftime("%I:%M") if law_firm.working_end_time.present? %></td>
          </tr>
        </tbody>
      </table>
    </font>
  </div>
</div>

<div class="section-title al-center">
  <h4><%= t ".lawyers" %></h4>
</div>
<div class="section-body padding-arround">
  <% if @lawyer_profiles.count > 0 %>
    <%= render("lawyers", lawyer_profiles: @lawyer_profiles) %>
  <% end %>
</div>

app/views/law_firms/_lawyer.html.erb
<% if lawyer_profile.present? %>
  <div class="row">
    <div class="col-md-2">
      <%= link_to lawyer_profile_path(lawyer_profile) do %>
        <%= image_tag lawyer_profile.account_avatar_url, size: "80x80", class: "pull-left" %>
      <% end %>
    </div>
    <div class="col-md-8">
      <p><%= link_to lawyer_profile.account_name, lawyer_profile_path(lawyer_profile) %></p>
      <p>
        <span class="stat_item" data-toggle="tooltip" title="<%= t '.reputation' %>">
          <i aria-hidden="true" class="fa fa-star" ></i> <%= lawyer_profile.reputation.to_i %>
        </span>
      </p>
      <p>
        <%= lawyer_profile.introduction.truncate(120) if lawyer_profile.introduction.present? %>
      </p>
    </div>
  </div>
<% end %>

app/views/law_firms/_lawyers.html.erb
<div class="pd-10">
  <% lawyer_profiles.each_slice(2) do |lawyer_1, lawyer_2| %>
    <div class="row section-item">
      <div class="col-md-6">
        <%= render "lawyer", lawyer_profile: lawyer_1 %>
      </div>
      <div class="col-md-6">
        <%= render "lawyer", lawyer_profile: lawyer_2 %>
      </div>
    </div>
  <% end %>
</div>

app/views/law_firms/_review.html.erb
<% if review.present? && review.account.present? %>
  <div class="section-item pd-10">
    <div class="row">
      <div class="col-md-2">
        <table>
          <tr>
            <td rowspan="2">
              <%= link_to account_path(review.account) do %>
                <%= image_tag review.account.account_avatar_url, size: "40x40", class: "no_margin" %>
              <% end %>
            </td>
            <td>
              <%= link_to review.account.name, account_path(review.account) %>
            </td>
          </tr>
          <tr>
            <td>
              <%= review.created_at.to_formatted_s(:short) %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-10">
        <p><%= review.content %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/law_firms/_reviews.html.erb
<div class="">
  <% if current_account.present? && current_account.User? %>
    <% new_review = Review.new %>
    <%= form_for [:user, new_review] do |f| %>
      <%= f.text_area :content, row: 3, place_holder: t(".input_review"), class: "form__input" %>
      <%= f.hidden_field :reviewable_type, value: law_firm.class %>
      <%= f.hidden_field :reviewable_id, value: law_firm.id %>

      <%= f.submit t(".submit"), class: "form__btn" %><br>
    <% end %>
  <% end %>

  <% if reviews.count > 0 %>
    <%= render partial: "review", collection: reviews, as: :review %>
  <% end %>
</div>

app/views/law_firms/_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <a data-toggle="tab" href="#info"><%= t ".infomation" %></a>
  </li>
  <li>
    <a data-toggle="tab" href="#articles"><%= t ".article" %></a>
  </li>
  <li>
    <a data-toggle="tab" href="#reviews"><%= t ".reviews" %></a>
  </li>
</ul>

<div class="tab-content">
  <div id="info" class="tab-pane fade in active">
    <%= render "law_firm_info", law_firm: law_firm %>
  </div>
  <div id="articles" class="tab-pane fade">
    <%= render partial: "shared/articles/article", collection: Article.where(account_id: law_firm.accounts.pluck(:id)), as: :article %>
  </div>
  <div id="reviews" class="tab-pane fade">
    <%= render "reviews", reviews: reviews, law_firm: law_firm %>
  </div>
</div>

app/views/law_firms/show.html.erb
<div class="col-md-9">
  <div class="row">
    <div class="col-md-12">
      <div class="avata-image">
        <%= image_tag @law_firm.lf_avatar_url, size: "120x120", class: "" %>
      </div>
      <div class="col-md-9" style="padding-bottom: 50px">
        <div>
          <h3><%= @law_firm.name %></h3>
        </div>
        <div class="glyphicon glyphicon-envelope">
          <%= @law_firm.email %>
        </div>
        </br>
        <div class="glyphicon glyphicon-flag">
          <%= @law_firm.created_at %>
        </div>
        </br>
        <div class="glyphicon glyphicon-map-marker">
          <%= @law_firm.address %>
        </div>
      </div>
    </div>
  </div>

  <div class="padding-arround">
    <%= render "tabs", law_firm: @law_firm, reviews: @reviews %>
  </div>
</div>

<div class="col-md-3">
<% if current_account.present? && current_account.can_join(@law_firm, @request_lf) %>
  <div class="section-body padding-arround">
    <%= render "shared/ranking/monthly_top_lawyer", accounts: @top_page.top_lawyers_ranking %>
    <%= form_tag request_law_firms_path(), method: :post do %>
      <%= hidden_field_tag law_firm_id: @law_firm.id %>
      <div class="actions">
        <%= submit_tag :Join %>
      </div>
    <% end %>
  </div>
<% end %>
<% if @law_profile.present? &&  @law_profile.can_out(@law_firm.id) %>
  <div class="section-body padding-arround">
    <%= link_to t(".out_law_firm"), lawyer_out_law_firm_path() , method: :delete, data: { confirm: t(".confirm") } %>
  </div>
<% end %>
</div>